name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Новые функции'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Исправления'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Документация'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧹 Прочее'
    labels:
      - 'chore'
      - 'misc'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
  default: patch

template: |
  ## Изменения
  
  $CHANGES
  
  ## Участники
  $CONTRIBUTORS
